version: '3.7'
services:

  postgres-db:
    image: postgres:14.5
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - my_external_volume:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    logging:
      driver: "none"
    links:
      - postgres-db:pdb

  # <THE-ABSOLUTE-PATH-TO-THIS-REPO>/keycloak/registration-event-listener/build
  # https://github.com/keycloak/keycloak/discussions/13516
  # https://www.keycloak.org/server/reverseproxy
  # https://stackoverflow.com/questions/72426072/how-to-configure-keycloak-18-running-http-only-in-production-mode
  keycloack:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: ${KEYCLOAK_CONTAINER_NAME}
    volumes:
      - ${KEYCLOAK_REGISTRATION_EVENT_LISTENER}:/opt/keycloak/providers/registration-event-listener.jar
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - postgres-db:pdb
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - KEYCLOAK_BTC_CHAT_REGISTER_USER_USERNAME=${KEYCLOAK_BTC_CHAT_REGISTER_USER_USERNAME}
      - KEYCLOAK_BTC_CHAT_REGISTER_USER_PASSWORD=${KEYCLOAK_BTC_CHAT_REGISTER_USER_PASSWORD}
      - KEYCLOAK_BTC_CHAT_URL=${KEYCLOAK_BTC_CHAT_URL}
    command: start-dev --db=${KEYCLOAK_DB} --db-username=${POSTGRES_USER} --db-password=${POSTGRES_PASSWORD} --db-url-host=pdb  --db-url-database=${KEYCLOAK_DB_SCHEMA}

volumes:
  my_external_volume :
    name: ${POSTGRES_VOLUME}
    external: true

